// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: waWebLabyrinthWaWasm/WAWebLabyrinthWaWasm.proto

package waWebLabyrinthWaWasm

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBackupInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecoveryCode  *string                `protobuf:"bytes,1,req,name=recoveryCode" json:"recoveryCode,omitempty"`
	UserID        *uint64                `protobuf:"varint,2,req,name=userID" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupInput) Reset() {
	*x = CreateBackupInput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupInput) ProtoMessage() {}

func (x *CreateBackupInput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupInput.ProtoReflect.Descriptor instead.
func (*CreateBackupInput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBackupInput) GetRecoveryCode() string {
	if x != nil && x.RecoveryCode != nil {
		return *x.RecoveryCode
	}
	return ""
}

func (x *CreateBackupInput) GetUserID() uint64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

type EncryptMessageInput struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EpochRootKey        []byte                 `protobuf:"bytes,1,req,name=epochRootKey" json:"epochRootKey,omitempty"`
	MailboxRootKey      []byte                 `protobuf:"bytes,2,req,name=mailboxRootKey" json:"mailboxRootKey,omitempty"`
	OrfClientState      []byte                 `protobuf:"bytes,3,req,name=orfClientState" json:"orfClientState,omitempty"`
	EpochAnonID         []byte                 `protobuf:"bytes,4,req,name=epochAnonID" json:"epochAnonID,omitempty"`
	EpochID             *uint64                `protobuf:"varint,5,req,name=epochID" json:"epochID,omitempty"`
	ThreadID            *string                `protobuf:"bytes,6,req,name=threadID" json:"threadID,omitempty"`
	WaCanonicalUserFbid *uint64                `protobuf:"varint,7,req,name=waCanonicalUserFbid" json:"waCanonicalUserFbid,omitempty"`
	TimestampMS         *uint64                `protobuf:"varint,8,req,name=timestampMS" json:"timestampMS,omitempty"`
	BackupID            *uint64                `protobuf:"varint,9,req,name=backupID" json:"backupID,omitempty"`
	PlaintextPayload    []byte                 `protobuf:"bytes,10,req,name=plaintextPayload" json:"plaintextPayload,omitempty"`
	StanzaID            *string                `protobuf:"bytes,11,req,name=stanzaID" json:"stanzaID,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EncryptMessageInput) Reset() {
	*x = EncryptMessageInput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptMessageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptMessageInput) ProtoMessage() {}

func (x *EncryptMessageInput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptMessageInput.ProtoReflect.Descriptor instead.
func (*EncryptMessageInput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptMessageInput) GetEpochRootKey() []byte {
	if x != nil {
		return x.EpochRootKey
	}
	return nil
}

func (x *EncryptMessageInput) GetMailboxRootKey() []byte {
	if x != nil {
		return x.MailboxRootKey
	}
	return nil
}

func (x *EncryptMessageInput) GetOrfClientState() []byte {
	if x != nil {
		return x.OrfClientState
	}
	return nil
}

func (x *EncryptMessageInput) GetEpochAnonID() []byte {
	if x != nil {
		return x.EpochAnonID
	}
	return nil
}

func (x *EncryptMessageInput) GetEpochID() uint64 {
	if x != nil && x.EpochID != nil {
		return *x.EpochID
	}
	return 0
}

func (x *EncryptMessageInput) GetThreadID() string {
	if x != nil && x.ThreadID != nil {
		return *x.ThreadID
	}
	return ""
}

func (x *EncryptMessageInput) GetWaCanonicalUserFbid() uint64 {
	if x != nil && x.WaCanonicalUserFbid != nil {
		return *x.WaCanonicalUserFbid
	}
	return 0
}

func (x *EncryptMessageInput) GetTimestampMS() uint64 {
	if x != nil && x.TimestampMS != nil {
		return *x.TimestampMS
	}
	return 0
}

func (x *EncryptMessageInput) GetBackupID() uint64 {
	if x != nil && x.BackupID != nil {
		return *x.BackupID
	}
	return 0
}

func (x *EncryptMessageInput) GetPlaintextPayload() []byte {
	if x != nil {
		return x.PlaintextPayload
	}
	return nil
}

func (x *EncryptMessageInput) GetStanzaID() string {
	if x != nil && x.StanzaID != nil {
		return *x.StanzaID
	}
	return ""
}

type DecryptMessageInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EpochRootKey      []byte                 `protobuf:"bytes,1,req,name=epochRootKey" json:"epochRootKey,omitempty"`
	EpochAnonID       []byte                 `protobuf:"bytes,2,req,name=epochAnonID" json:"epochAnonID,omitempty"`
	ThreadID          *string                `protobuf:"bytes,3,req,name=threadID" json:"threadID,omitempty"`
	EncryptionVersion *int32                 `protobuf:"varint,4,req,name=encryptionVersion" json:"encryptionVersion,omitempty"`
	Ciphertext        []byte                 `protobuf:"bytes,5,req,name=ciphertext" json:"ciphertext,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DecryptMessageInput) Reset() {
	*x = DecryptMessageInput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptMessageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptMessageInput) ProtoMessage() {}

func (x *DecryptMessageInput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptMessageInput.ProtoReflect.Descriptor instead.
func (*DecryptMessageInput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{2}
}

func (x *DecryptMessageInput) GetEpochRootKey() []byte {
	if x != nil {
		return x.EpochRootKey
	}
	return nil
}

func (x *DecryptMessageInput) GetEpochAnonID() []byte {
	if x != nil {
		return x.EpochAnonID
	}
	return nil
}

func (x *DecryptMessageInput) GetThreadID() string {
	if x != nil && x.ThreadID != nil {
		return *x.ThreadID
	}
	return ""
}

func (x *DecryptMessageInput) GetEncryptionVersion() int32 {
	if x != nil && x.EncryptionVersion != nil {
		return *x.EncryptionVersion
	}
	return 0
}

func (x *DecryptMessageInput) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type OrfThreadIdInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrfClientState []byte                 `protobuf:"bytes,1,req,name=orfClientState" json:"orfClientState,omitempty"`
	ThreadID       *string                `protobuf:"bytes,2,req,name=threadID" json:"threadID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrfThreadIdInput) Reset() {
	*x = OrfThreadIdInput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrfThreadIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrfThreadIdInput) ProtoMessage() {}

func (x *OrfThreadIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrfThreadIdInput.ProtoReflect.Descriptor instead.
func (*OrfThreadIdInput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{3}
}

func (x *OrfThreadIdInput) GetOrfClientState() []byte {
	if x != nil {
		return x.OrfClientState
	}
	return nil
}

func (x *OrfThreadIdInput) GetThreadID() string {
	if x != nil && x.ThreadID != nil {
		return *x.ThreadID
	}
	return ""
}

type DeriveMessageKeyInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpochRootKey  []byte                 `protobuf:"bytes,1,req,name=epochRootKey" json:"epochRootKey,omitempty"`
	EpochAnonID   []byte                 `protobuf:"bytes,2,req,name=epochAnonID" json:"epochAnonID,omitempty"`
	ThreadID      *string                `protobuf:"bytes,3,req,name=threadID" json:"threadID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveMessageKeyInput) Reset() {
	*x = DeriveMessageKeyInput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveMessageKeyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveMessageKeyInput) ProtoMessage() {}

func (x *DeriveMessageKeyInput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveMessageKeyInput.ProtoReflect.Descriptor instead.
func (*DeriveMessageKeyInput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{4}
}

func (x *DeriveMessageKeyInput) GetEpochRootKey() []byte {
	if x != nil {
		return x.EpochRootKey
	}
	return nil
}

func (x *DeriveMessageKeyInput) GetEpochAnonID() []byte {
	if x != nil {
		return x.EpochAnonID
	}
	return nil
}

func (x *DeriveMessageKeyInput) GetThreadID() string {
	if x != nil && x.ThreadID != nil {
		return *x.ThreadID
	}
	return ""
}

type DeviceOutput struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	PublicKey                   []byte                 `protobuf:"bytes,1,req,name=publicKey" json:"publicKey,omitempty"`
	EpochAuthPublicKey          []byte                 `protobuf:"bytes,2,req,name=epochAuthPublicKey" json:"epochAuthPublicKey,omitempty"`
	EpochAuthPublicKeySig       []byte                 `protobuf:"bytes,3,req,name=epochAuthPublicKeySig" json:"epochAuthPublicKeySig,omitempty"`
	EpochStoragePublicKey       []byte                 `protobuf:"bytes,4,req,name=epochStoragePublicKey" json:"epochStoragePublicKey,omitempty"`
	EpochStoragePublicKeySig    []byte                 `protobuf:"bytes,5,req,name=epochStoragePublicKeySig" json:"epochStoragePublicKeySig,omitempty"`
	SupportedEncryptionVersions []int32                `protobuf:"varint,6,rep,name=supportedEncryptionVersions" json:"supportedEncryptionVersions,omitempty"`
	EncryptionVersionSignature  []byte                 `protobuf:"bytes,7,req,name=encryptionVersionSignature" json:"encryptionVersionSignature,omitempty"`
	ClientVersion               *int32                 `protobuf:"varint,8,req,name=clientVersion" json:"clientVersion,omitempty"`
	OcmfClientState             []byte                 `protobuf:"bytes,9,req,name=ocmfClientState" json:"ocmfClientState,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DeviceOutput) Reset() {
	*x = DeviceOutput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceOutput) ProtoMessage() {}

func (x *DeviceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceOutput.ProtoReflect.Descriptor instead.
func (*DeviceOutput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceOutput) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DeviceOutput) GetEpochAuthPublicKey() []byte {
	if x != nil {
		return x.EpochAuthPublicKey
	}
	return nil
}

func (x *DeviceOutput) GetEpochAuthPublicKeySig() []byte {
	if x != nil {
		return x.EpochAuthPublicKeySig
	}
	return nil
}

func (x *DeviceOutput) GetEpochStoragePublicKey() []byte {
	if x != nil {
		return x.EpochStoragePublicKey
	}
	return nil
}

func (x *DeviceOutput) GetEpochStoragePublicKeySig() []byte {
	if x != nil {
		return x.EpochStoragePublicKeySig
	}
	return nil
}

func (x *DeviceOutput) GetSupportedEncryptionVersions() []int32 {
	if x != nil {
		return x.SupportedEncryptionVersions
	}
	return nil
}

func (x *DeviceOutput) GetEncryptionVersionSignature() []byte {
	if x != nil {
		return x.EncryptionVersionSignature
	}
	return nil
}

func (x *DeviceOutput) GetClientVersion() int32 {
	if x != nil && x.ClientVersion != nil {
		return *x.ClientVersion
	}
	return 0
}

func (x *DeviceOutput) GetOcmfClientState() []byte {
	if x != nil {
		return x.OcmfClientState
	}
	return nil
}

type EncryptedSecretValuesOutput struct {
	state                                 protoimpl.MessageState `protogen:"open.v1"`
	EncryptedDevicePrivateKey             []byte                 `protobuf:"bytes,1,req,name=encryptedDevicePrivateKey" json:"encryptedDevicePrivateKey,omitempty"`
	EncryptedObliviousValidationTokenBlob []byte                 `protobuf:"bytes,2,req,name=encryptedObliviousValidationTokenBlob" json:"encryptedObliviousValidationTokenBlob,omitempty"`
	EncryptedEpochStoragePrivateKey       []byte                 `protobuf:"bytes,3,req,name=encryptedEpochStoragePrivateKey" json:"encryptedEpochStoragePrivateKey,omitempty"`
	EncryptedOcmfClientState              []byte                 `protobuf:"bytes,4,req,name=encryptedOcmfClientState" json:"encryptedOcmfClientState,omitempty"`
	EncryptedOrfClientStateV2             []byte                 `protobuf:"bytes,5,opt,name=encryptedOrfClientStateV2" json:"encryptedOrfClientStateV2,omitempty"`
	EncryptedMailboxRootKeyBlob           []byte                 `protobuf:"bytes,6,req,name=encryptedMailboxRootKeyBlob" json:"encryptedMailboxRootKeyBlob,omitempty"`
	EncryptedEpochAnonID                  []byte                 `protobuf:"bytes,7,req,name=encryptedEpochAnonID" json:"encryptedEpochAnonID,omitempty"`
	EncryptedEpochRootKey                 []byte                 `protobuf:"bytes,8,req,name=encryptedEpochRootKey" json:"encryptedEpochRootKey,omitempty"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *EncryptedSecretValuesOutput) Reset() {
	*x = EncryptedSecretValuesOutput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedSecretValuesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedSecretValuesOutput) ProtoMessage() {}

func (x *EncryptedSecretValuesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedSecretValuesOutput.ProtoReflect.Descriptor instead.
func (*EncryptedSecretValuesOutput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{6}
}

func (x *EncryptedSecretValuesOutput) GetEncryptedDevicePrivateKey() []byte {
	if x != nil {
		return x.EncryptedDevicePrivateKey
	}
	return nil
}

func (x *EncryptedSecretValuesOutput) GetEncryptedObliviousValidationTokenBlob() []byte {
	if x != nil {
		return x.EncryptedObliviousValidationTokenBlob
	}
	return nil
}

func (x *EncryptedSecretValuesOutput) GetEncryptedEpochStoragePrivateKey() []byte {
	if x != nil {
		return x.EncryptedEpochStoragePrivateKey
	}
	return nil
}

func (x *EncryptedSecretValuesOutput) GetEncryptedOcmfClientState() []byte {
	if x != nil {
		return x.EncryptedOcmfClientState
	}
	return nil
}

func (x *EncryptedSecretValuesOutput) GetEncryptedOrfClientStateV2() []byte {
	if x != nil {
		return x.EncryptedOrfClientStateV2
	}
	return nil
}

func (x *EncryptedSecretValuesOutput) GetEncryptedMailboxRootKeyBlob() []byte {
	if x != nil {
		return x.EncryptedMailboxRootKeyBlob
	}
	return nil
}

func (x *EncryptedSecretValuesOutput) GetEncryptedEpochAnonID() []byte {
	if x != nil {
		return x.EncryptedEpochAnonID
	}
	return nil
}

func (x *EncryptedSecretValuesOutput) GetEncryptedEpochRootKey() []byte {
	if x != nil {
		return x.EncryptedEpochRootKey
	}
	return nil
}

type VirtualDeviceOutput struct {
	state                      protoimpl.MessageState       `protogen:"open.v1"`
	VdID                       []byte                       `protobuf:"bytes,1,req,name=vdID" json:"vdID,omitempty"`
	VdPublicKey                []byte                       `protobuf:"bytes,2,req,name=vdPublicKey" json:"vdPublicKey,omitempty"`
	VdEpochStoragePublicKey    []byte                       `protobuf:"bytes,3,req,name=vdEpochStoragePublicKey" json:"vdEpochStoragePublicKey,omitempty"`
	VdEpochStoragePublicKeySig []byte                       `protobuf:"bytes,4,req,name=vdEpochStoragePublicKeySig" json:"vdEpochStoragePublicKeySig,omitempty"`
	OcmfRotationToken          []byte                       `protobuf:"bytes,5,req,name=ocmfRotationToken" json:"ocmfRotationToken,omitempty"`
	DeviceEpochHmac            []byte                       `protobuf:"bytes,6,req,name=deviceEpochHmac" json:"deviceEpochHmac,omitempty"`
	EncryptedSecretValues      *EncryptedSecretValuesOutput `protobuf:"bytes,7,req,name=encryptedSecretValues" json:"encryptedSecretValues,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *VirtualDeviceOutput) Reset() {
	*x = VirtualDeviceOutput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualDeviceOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualDeviceOutput) ProtoMessage() {}

func (x *VirtualDeviceOutput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualDeviceOutput.ProtoReflect.Descriptor instead.
func (*VirtualDeviceOutput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{7}
}

func (x *VirtualDeviceOutput) GetVdID() []byte {
	if x != nil {
		return x.VdID
	}
	return nil
}

func (x *VirtualDeviceOutput) GetVdPublicKey() []byte {
	if x != nil {
		return x.VdPublicKey
	}
	return nil
}

func (x *VirtualDeviceOutput) GetVdEpochStoragePublicKey() []byte {
	if x != nil {
		return x.VdEpochStoragePublicKey
	}
	return nil
}

func (x *VirtualDeviceOutput) GetVdEpochStoragePublicKeySig() []byte {
	if x != nil {
		return x.VdEpochStoragePublicKeySig
	}
	return nil
}

func (x *VirtualDeviceOutput) GetOcmfRotationToken() []byte {
	if x != nil {
		return x.OcmfRotationToken
	}
	return nil
}

func (x *VirtualDeviceOutput) GetDeviceEpochHmac() []byte {
	if x != nil {
		return x.DeviceEpochHmac
	}
	return nil
}

func (x *VirtualDeviceOutput) GetEncryptedSecretValues() *EncryptedSecretValuesOutput {
	if x != nil {
		return x.EncryptedSecretValues
	}
	return nil
}

type Epoch0Output struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	EpochFbid               *uint64                `protobuf:"varint,1,req,name=epochFbid" json:"epochFbid,omitempty"`
	EpochAnonID             []byte                 `protobuf:"bytes,2,req,name=epochAnonID" json:"epochAnonID,omitempty"`
	EpochData               []byte                 `protobuf:"bytes,3,req,name=epochData" json:"epochData,omitempty"`
	WrappedRootKeyForSelf   []byte                 `protobuf:"bytes,4,req,name=wrappedRootKeyForSelf" json:"wrappedRootKeyForSelf,omitempty"`
	EpochSignature          []byte                 `protobuf:"bytes,5,req,name=epochSignature" json:"epochSignature,omitempty"`
	EpochRootKeyFingerprint []byte                 `protobuf:"bytes,6,req,name=epochRootKeyFingerprint" json:"epochRootKeyFingerprint,omitempty"`
	EpochRootKey            []byte                 `protobuf:"bytes,7,opt,name=epochRootKey" json:"epochRootKey,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Epoch0Output) Reset() {
	*x = Epoch0Output{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Epoch0Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Epoch0Output) ProtoMessage() {}

func (x *Epoch0Output) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Epoch0Output.ProtoReflect.Descriptor instead.
func (*Epoch0Output) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{8}
}

func (x *Epoch0Output) GetEpochFbid() uint64 {
	if x != nil && x.EpochFbid != nil {
		return *x.EpochFbid
	}
	return 0
}

func (x *Epoch0Output) GetEpochAnonID() []byte {
	if x != nil {
		return x.EpochAnonID
	}
	return nil
}

func (x *Epoch0Output) GetEpochData() []byte {
	if x != nil {
		return x.EpochData
	}
	return nil
}

func (x *Epoch0Output) GetWrappedRootKeyForSelf() []byte {
	if x != nil {
		return x.WrappedRootKeyForSelf
	}
	return nil
}

func (x *Epoch0Output) GetEpochSignature() []byte {
	if x != nil {
		return x.EpochSignature
	}
	return nil
}

func (x *Epoch0Output) GetEpochRootKeyFingerprint() []byte {
	if x != nil {
		return x.EpochRootKeyFingerprint
	}
	return nil
}

func (x *Epoch0Output) GetEpochRootKey() []byte {
	if x != nil {
		return x.EpochRootKey
	}
	return nil
}

type CreateBackupOutput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Device         *DeviceOutput          `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
	VirtualDevice  *VirtualDeviceOutput   `protobuf:"bytes,2,opt,name=virtualDevice" json:"virtualDevice,omitempty"`
	Epoch0         *Epoch0Output          `protobuf:"bytes,3,opt,name=epoch0" json:"epoch0,omitempty"`
	MailboxRootKey []byte                 `protobuf:"bytes,4,opt,name=mailboxRootKey" json:"mailboxRootKey,omitempty"`
	Error          *string                `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBackupOutput) Reset() {
	*x = CreateBackupOutput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupOutput) ProtoMessage() {}

func (x *CreateBackupOutput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupOutput.ProtoReflect.Descriptor instead.
func (*CreateBackupOutput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBackupOutput) GetDevice() *DeviceOutput {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *CreateBackupOutput) GetVirtualDevice() *VirtualDeviceOutput {
	if x != nil {
		return x.VirtualDevice
	}
	return nil
}

func (x *CreateBackupOutput) GetEpoch0() *Epoch0Output {
	if x != nil {
		return x.Epoch0
	}
	return nil
}

func (x *CreateBackupOutput) GetMailboxRootKey() []byte {
	if x != nil {
		return x.MailboxRootKey
	}
	return nil
}

func (x *CreateBackupOutput) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type EncryptMessageOutput struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EncryptedProtobuf  []byte                 `protobuf:"bytes,1,opt,name=encryptedProtobuf" json:"encryptedProtobuf,omitempty"`
	OrfThreadID        []byte                 `protobuf:"bytes,2,opt,name=orfThreadID" json:"orfThreadID,omitempty"`
	ValueSecretRef     *string                `protobuf:"bytes,3,opt,name=valueSecretRef" json:"valueSecretRef,omitempty"`
	OfflineThreadingID *uint64                `protobuf:"varint,4,opt,name=offlineThreadingID" json:"offlineThreadingID,omitempty"`
	TimestampMS        *uint64                `protobuf:"varint,5,opt,name=timestampMS" json:"timestampMS,omitempty"`
	MessageKey         []byte                 `protobuf:"bytes,6,opt,name=messageKey" json:"messageKey,omitempty"`
	Error              *string                `protobuf:"bytes,7,opt,name=error" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EncryptMessageOutput) Reset() {
	*x = EncryptMessageOutput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptMessageOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptMessageOutput) ProtoMessage() {}

func (x *EncryptMessageOutput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptMessageOutput.ProtoReflect.Descriptor instead.
func (*EncryptMessageOutput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{10}
}

func (x *EncryptMessageOutput) GetEncryptedProtobuf() []byte {
	if x != nil {
		return x.EncryptedProtobuf
	}
	return nil
}

func (x *EncryptMessageOutput) GetOrfThreadID() []byte {
	if x != nil {
		return x.OrfThreadID
	}
	return nil
}

func (x *EncryptMessageOutput) GetValueSecretRef() string {
	if x != nil && x.ValueSecretRef != nil {
		return *x.ValueSecretRef
	}
	return ""
}

func (x *EncryptMessageOutput) GetOfflineThreadingID() uint64 {
	if x != nil && x.OfflineThreadingID != nil {
		return *x.OfflineThreadingID
	}
	return 0
}

func (x *EncryptMessageOutput) GetTimestampMS() uint64 {
	if x != nil && x.TimestampMS != nil {
		return *x.TimestampMS
	}
	return 0
}

func (x *EncryptMessageOutput) GetMessageKey() []byte {
	if x != nil {
		return x.MessageKey
	}
	return nil
}

func (x *EncryptMessageOutput) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DecryptMessageOutput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlaintextPayload []byte                 `protobuf:"bytes,1,opt,name=plaintextPayload" json:"plaintextPayload,omitempty"`
	Error            *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DecryptMessageOutput) Reset() {
	*x = DecryptMessageOutput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptMessageOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptMessageOutput) ProtoMessage() {}

func (x *DecryptMessageOutput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptMessageOutput.ProtoReflect.Descriptor instead.
func (*DecryptMessageOutput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{11}
}

func (x *DecryptMessageOutput) GetPlaintextPayload() []byte {
	if x != nil {
		return x.PlaintextPayload
	}
	return nil
}

func (x *DecryptMessageOutput) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type OrfThreadIdOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrfThreadID   []byte                 `protobuf:"bytes,1,opt,name=orfThreadID" json:"orfThreadID,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrfThreadIdOutput) Reset() {
	*x = OrfThreadIdOutput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrfThreadIdOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrfThreadIdOutput) ProtoMessage() {}

func (x *OrfThreadIdOutput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrfThreadIdOutput.ProtoReflect.Descriptor instead.
func (*OrfThreadIdOutput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{12}
}

func (x *OrfThreadIdOutput) GetOrfThreadID() []byte {
	if x != nil {
		return x.OrfThreadID
	}
	return nil
}

func (x *OrfThreadIdOutput) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type DeriveMessageKeyOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageKey    []byte                 `protobuf:"bytes,1,opt,name=messageKey" json:"messageKey,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveMessageKeyOutput) Reset() {
	*x = DeriveMessageKeyOutput{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveMessageKeyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveMessageKeyOutput) ProtoMessage() {}

func (x *DeriveMessageKeyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveMessageKeyOutput.ProtoReflect.Descriptor instead.
func (*DeriveMessageKeyOutput) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{13}
}

func (x *DeriveMessageKeyOutput) GetMessageKey() []byte {
	if x != nil {
		return x.MessageKey
	}
	return nil
}

func (x *DeriveMessageKeyOutput) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type LabyrinthWaCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to CommandInput:
	//
	//	*LabyrinthWaCommand_CreateBackupInput
	//	*LabyrinthWaCommand_EncryptMessageInput
	//	*LabyrinthWaCommand_DecryptMessageInput
	//	*LabyrinthWaCommand_OrfThreadIDInput
	//	*LabyrinthWaCommand_DeriveMessageKeyInput
	CommandInput  isLabyrinthWaCommand_CommandInput `protobuf_oneof:"commandInput"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabyrinthWaCommand) Reset() {
	*x = LabyrinthWaCommand{}
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabyrinthWaCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabyrinthWaCommand) ProtoMessage() {}

func (x *LabyrinthWaCommand) ProtoReflect() protoreflect.Message {
	mi := &file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabyrinthWaCommand.ProtoReflect.Descriptor instead.
func (*LabyrinthWaCommand) Descriptor() ([]byte, []int) {
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP(), []int{14}
}

func (x *LabyrinthWaCommand) GetCommandInput() isLabyrinthWaCommand_CommandInput {
	if x != nil {
		return x.CommandInput
	}
	return nil
}

func (x *LabyrinthWaCommand) GetCreateBackupInput() *CreateBackupInput {
	if x != nil {
		if x, ok := x.CommandInput.(*LabyrinthWaCommand_CreateBackupInput); ok {
			return x.CreateBackupInput
		}
	}
	return nil
}

func (x *LabyrinthWaCommand) GetEncryptMessageInput() *EncryptMessageInput {
	if x != nil {
		if x, ok := x.CommandInput.(*LabyrinthWaCommand_EncryptMessageInput); ok {
			return x.EncryptMessageInput
		}
	}
	return nil
}

func (x *LabyrinthWaCommand) GetDecryptMessageInput() *DecryptMessageInput {
	if x != nil {
		if x, ok := x.CommandInput.(*LabyrinthWaCommand_DecryptMessageInput); ok {
			return x.DecryptMessageInput
		}
	}
	return nil
}

func (x *LabyrinthWaCommand) GetOrfThreadIDInput() *OrfThreadIdInput {
	if x != nil {
		if x, ok := x.CommandInput.(*LabyrinthWaCommand_OrfThreadIDInput); ok {
			return x.OrfThreadIDInput
		}
	}
	return nil
}

func (x *LabyrinthWaCommand) GetDeriveMessageKeyInput() *DeriveMessageKeyInput {
	if x != nil {
		if x, ok := x.CommandInput.(*LabyrinthWaCommand_DeriveMessageKeyInput); ok {
			return x.DeriveMessageKeyInput
		}
	}
	return nil
}

type isLabyrinthWaCommand_CommandInput interface {
	isLabyrinthWaCommand_CommandInput()
}

type LabyrinthWaCommand_CreateBackupInput struct {
	CreateBackupInput *CreateBackupInput `protobuf:"bytes,1,opt,name=createBackupInput,oneof"`
}

type LabyrinthWaCommand_EncryptMessageInput struct {
	EncryptMessageInput *EncryptMessageInput `protobuf:"bytes,2,opt,name=encryptMessageInput,oneof"`
}

type LabyrinthWaCommand_DecryptMessageInput struct {
	DecryptMessageInput *DecryptMessageInput `protobuf:"bytes,3,opt,name=decryptMessageInput,oneof"`
}

type LabyrinthWaCommand_OrfThreadIDInput struct {
	OrfThreadIDInput *OrfThreadIdInput `protobuf:"bytes,4,opt,name=orfThreadIDInput,oneof"`
}

type LabyrinthWaCommand_DeriveMessageKeyInput struct {
	DeriveMessageKeyInput *DeriveMessageKeyInput `protobuf:"bytes,5,opt,name=deriveMessageKeyInput,oneof"`
}

func (*LabyrinthWaCommand_CreateBackupInput) isLabyrinthWaCommand_CommandInput() {}

func (*LabyrinthWaCommand_EncryptMessageInput) isLabyrinthWaCommand_CommandInput() {}

func (*LabyrinthWaCommand_DecryptMessageInput) isLabyrinthWaCommand_CommandInput() {}

func (*LabyrinthWaCommand_OrfThreadIDInput) isLabyrinthWaCommand_CommandInput() {}

func (*LabyrinthWaCommand_DeriveMessageKeyInput) isLabyrinthWaCommand_CommandInput() {}

var File_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto protoreflect.FileDescriptor

const file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDesc = "" +
	"\n" +
	"/waWebLabyrinthWaWasm/WAWebLabyrinthWaWasm.proto\x12\x14WAWebLabyrinthWaWasm\"O\n" +
	"\x11CreateBackupInput\x12\"\n" +
	"\frecoveryCode\x18\x01 \x02(\tR\frecoveryCode\x12\x16\n" +
	"\x06userID\x18\x02 \x02(\x04R\x06userID\"\x99\x03\n" +
	"\x13EncryptMessageInput\x12\"\n" +
	"\fepochRootKey\x18\x01 \x02(\fR\fepochRootKey\x12&\n" +
	"\x0emailboxRootKey\x18\x02 \x02(\fR\x0emailboxRootKey\x12&\n" +
	"\x0eorfClientState\x18\x03 \x02(\fR\x0eorfClientState\x12 \n" +
	"\vepochAnonID\x18\x04 \x02(\fR\vepochAnonID\x12\x18\n" +
	"\aepochID\x18\x05 \x02(\x04R\aepochID\x12\x1a\n" +
	"\bthreadID\x18\x06 \x02(\tR\bthreadID\x120\n" +
	"\x13waCanonicalUserFbid\x18\a \x02(\x04R\x13waCanonicalUserFbid\x12 \n" +
	"\vtimestampMS\x18\b \x02(\x04R\vtimestampMS\x12\x1a\n" +
	"\bbackupID\x18\t \x02(\x04R\bbackupID\x12*\n" +
	"\x10plaintextPayload\x18\n" +
	" \x02(\fR\x10plaintextPayload\x12\x1a\n" +
	"\bstanzaID\x18\v \x02(\tR\bstanzaID\"\xc5\x01\n" +
	"\x13DecryptMessageInput\x12\"\n" +
	"\fepochRootKey\x18\x01 \x02(\fR\fepochRootKey\x12 \n" +
	"\vepochAnonID\x18\x02 \x02(\fR\vepochAnonID\x12\x1a\n" +
	"\bthreadID\x18\x03 \x02(\tR\bthreadID\x12,\n" +
	"\x11encryptionVersion\x18\x04 \x02(\x05R\x11encryptionVersion\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x05 \x02(\fR\n" +
	"ciphertext\"V\n" +
	"\x10OrfThreadIdInput\x12&\n" +
	"\x0eorfClientState\x18\x01 \x02(\fR\x0eorfClientState\x12\x1a\n" +
	"\bthreadID\x18\x02 \x02(\tR\bthreadID\"y\n" +
	"\x15DeriveMessageKeyInput\x12\"\n" +
	"\fepochRootKey\x18\x01 \x02(\fR\fepochRootKey\x12 \n" +
	"\vepochAnonID\x18\x02 \x02(\fR\vepochAnonID\x12\x1a\n" +
	"\bthreadID\x18\x03 \x02(\tR\bthreadID\"\xd6\x03\n" +
	"\fDeviceOutput\x12\x1c\n" +
	"\tpublicKey\x18\x01 \x02(\fR\tpublicKey\x12.\n" +
	"\x12epochAuthPublicKey\x18\x02 \x02(\fR\x12epochAuthPublicKey\x124\n" +
	"\x15epochAuthPublicKeySig\x18\x03 \x02(\fR\x15epochAuthPublicKeySig\x124\n" +
	"\x15epochStoragePublicKey\x18\x04 \x02(\fR\x15epochStoragePublicKey\x12:\n" +
	"\x18epochStoragePublicKeySig\x18\x05 \x02(\fR\x18epochStoragePublicKeySig\x12@\n" +
	"\x1bsupportedEncryptionVersions\x18\x06 \x03(\x05R\x1bsupportedEncryptionVersions\x12>\n" +
	"\x1aencryptionVersionSignature\x18\a \x02(\fR\x1aencryptionVersionSignature\x12$\n" +
	"\rclientVersion\x18\b \x02(\x05R\rclientVersion\x12(\n" +
	"\x0focmfClientState\x18\t \x02(\fR\x0focmfClientState\"\xa1\x04\n" +
	"\x1bEncryptedSecretValuesOutput\x12<\n" +
	"\x19encryptedDevicePrivateKey\x18\x01 \x02(\fR\x19encryptedDevicePrivateKey\x12T\n" +
	"%encryptedObliviousValidationTokenBlob\x18\x02 \x02(\fR%encryptedObliviousValidationTokenBlob\x12H\n" +
	"\x1fencryptedEpochStoragePrivateKey\x18\x03 \x02(\fR\x1fencryptedEpochStoragePrivateKey\x12:\n" +
	"\x18encryptedOcmfClientState\x18\x04 \x02(\fR\x18encryptedOcmfClientState\x12<\n" +
	"\x19encryptedOrfClientStateV2\x18\x05 \x01(\fR\x19encryptedOrfClientStateV2\x12@\n" +
	"\x1bencryptedMailboxRootKeyBlob\x18\x06 \x02(\fR\x1bencryptedMailboxRootKeyBlob\x122\n" +
	"\x14encryptedEpochAnonID\x18\a \x02(\fR\x14encryptedEpochAnonID\x124\n" +
	"\x15encryptedEpochRootKey\x18\b \x02(\fR\x15encryptedEpochRootKey\"\x86\x03\n" +
	"\x13VirtualDeviceOutput\x12\x12\n" +
	"\x04vdID\x18\x01 \x02(\fR\x04vdID\x12 \n" +
	"\vvdPublicKey\x18\x02 \x02(\fR\vvdPublicKey\x128\n" +
	"\x17vdEpochStoragePublicKey\x18\x03 \x02(\fR\x17vdEpochStoragePublicKey\x12>\n" +
	"\x1avdEpochStoragePublicKeySig\x18\x04 \x02(\fR\x1avdEpochStoragePublicKeySig\x12,\n" +
	"\x11ocmfRotationToken\x18\x05 \x02(\fR\x11ocmfRotationToken\x12(\n" +
	"\x0fdeviceEpochHmac\x18\x06 \x02(\fR\x0fdeviceEpochHmac\x12g\n" +
	"\x15encryptedSecretValues\x18\a \x02(\v21.WAWebLabyrinthWaWasm.EncryptedSecretValuesOutputR\x15encryptedSecretValues\"\xa8\x02\n" +
	"\fEpoch0Output\x12\x1c\n" +
	"\tepochFbid\x18\x01 \x02(\x04R\tepochFbid\x12 \n" +
	"\vepochAnonID\x18\x02 \x02(\fR\vepochAnonID\x12\x1c\n" +
	"\tepochData\x18\x03 \x02(\fR\tepochData\x124\n" +
	"\x15wrappedRootKeyForSelf\x18\x04 \x02(\fR\x15wrappedRootKeyForSelf\x12&\n" +
	"\x0eepochSignature\x18\x05 \x02(\fR\x0eepochSignature\x128\n" +
	"\x17epochRootKeyFingerprint\x18\x06 \x02(\fR\x17epochRootKeyFingerprint\x12\"\n" +
	"\fepochRootKey\x18\a \x01(\fR\fepochRootKey\"\x9b\x02\n" +
	"\x12CreateBackupOutput\x12:\n" +
	"\x06device\x18\x01 \x01(\v2\".WAWebLabyrinthWaWasm.DeviceOutputR\x06device\x12O\n" +
	"\rvirtualDevice\x18\x02 \x01(\v2).WAWebLabyrinthWaWasm.VirtualDeviceOutputR\rvirtualDevice\x12:\n" +
	"\x06epoch0\x18\x03 \x01(\v2\".WAWebLabyrinthWaWasm.Epoch0OutputR\x06epoch0\x12&\n" +
	"\x0emailboxRootKey\x18\x04 \x01(\fR\x0emailboxRootKey\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x96\x02\n" +
	"\x14EncryptMessageOutput\x12,\n" +
	"\x11encryptedProtobuf\x18\x01 \x01(\fR\x11encryptedProtobuf\x12 \n" +
	"\vorfThreadID\x18\x02 \x01(\fR\vorfThreadID\x12&\n" +
	"\x0evalueSecretRef\x18\x03 \x01(\tR\x0evalueSecretRef\x12.\n" +
	"\x12offlineThreadingID\x18\x04 \x01(\x04R\x12offlineThreadingID\x12 \n" +
	"\vtimestampMS\x18\x05 \x01(\x04R\vtimestampMS\x12\x1e\n" +
	"\n" +
	"messageKey\x18\x06 \x01(\fR\n" +
	"messageKey\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"X\n" +
	"\x14DecryptMessageOutput\x12*\n" +
	"\x10plaintextPayload\x18\x01 \x01(\fR\x10plaintextPayload\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\x11OrfThreadIdOutput\x12 \n" +
	"\vorfThreadID\x18\x01 \x01(\fR\vorfThreadID\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"N\n" +
	"\x16DeriveMessageKeyOutput\x12\x1e\n" +
	"\n" +
	"messageKey\x18\x01 \x01(\fR\n" +
	"messageKey\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xf6\x03\n" +
	"\x12LabyrinthWaCommand\x12W\n" +
	"\x11createBackupInput\x18\x01 \x01(\v2'.WAWebLabyrinthWaWasm.CreateBackupInputH\x00R\x11createBackupInput\x12]\n" +
	"\x13encryptMessageInput\x18\x02 \x01(\v2).WAWebLabyrinthWaWasm.EncryptMessageInputH\x00R\x13encryptMessageInput\x12]\n" +
	"\x13decryptMessageInput\x18\x03 \x01(\v2).WAWebLabyrinthWaWasm.DecryptMessageInputH\x00R\x13decryptMessageInput\x12T\n" +
	"\x10orfThreadIDInput\x18\x04 \x01(\v2&.WAWebLabyrinthWaWasm.OrfThreadIdInputH\x00R\x10orfThreadIDInput\x12c\n" +
	"\x15deriveMessageKeyInput\x18\x05 \x01(\v2+.WAWebLabyrinthWaWasm.DeriveMessageKeyInputH\x00R\x15deriveMessageKeyInputB\x0e\n" +
	"\fcommandInputB0Z.go.mau.fi/whatsmeow/proto/waWebLabyrinthWaWasm"

var (
	file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescOnce sync.Once
	file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescData []byte
)

func file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescGZIP() []byte {
	file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescOnce.Do(func() {
		file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDesc), len(file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDesc)))
	})
	return file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDescData
}

var file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_goTypes = []any{
	(*CreateBackupInput)(nil),           // 0: WAWebLabyrinthWaWasm.CreateBackupInput
	(*EncryptMessageInput)(nil),         // 1: WAWebLabyrinthWaWasm.EncryptMessageInput
	(*DecryptMessageInput)(nil),         // 2: WAWebLabyrinthWaWasm.DecryptMessageInput
	(*OrfThreadIdInput)(nil),            // 3: WAWebLabyrinthWaWasm.OrfThreadIdInput
	(*DeriveMessageKeyInput)(nil),       // 4: WAWebLabyrinthWaWasm.DeriveMessageKeyInput
	(*DeviceOutput)(nil),                // 5: WAWebLabyrinthWaWasm.DeviceOutput
	(*EncryptedSecretValuesOutput)(nil), // 6: WAWebLabyrinthWaWasm.EncryptedSecretValuesOutput
	(*VirtualDeviceOutput)(nil),         // 7: WAWebLabyrinthWaWasm.VirtualDeviceOutput
	(*Epoch0Output)(nil),                // 8: WAWebLabyrinthWaWasm.Epoch0Output
	(*CreateBackupOutput)(nil),          // 9: WAWebLabyrinthWaWasm.CreateBackupOutput
	(*EncryptMessageOutput)(nil),        // 10: WAWebLabyrinthWaWasm.EncryptMessageOutput
	(*DecryptMessageOutput)(nil),        // 11: WAWebLabyrinthWaWasm.DecryptMessageOutput
	(*OrfThreadIdOutput)(nil),           // 12: WAWebLabyrinthWaWasm.OrfThreadIdOutput
	(*DeriveMessageKeyOutput)(nil),      // 13: WAWebLabyrinthWaWasm.DeriveMessageKeyOutput
	(*LabyrinthWaCommand)(nil),          // 14: WAWebLabyrinthWaWasm.LabyrinthWaCommand
}
var file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_depIdxs = []int32{
	6, // 0: WAWebLabyrinthWaWasm.VirtualDeviceOutput.encryptedSecretValues:type_name -> WAWebLabyrinthWaWasm.EncryptedSecretValuesOutput
	5, // 1: WAWebLabyrinthWaWasm.CreateBackupOutput.device:type_name -> WAWebLabyrinthWaWasm.DeviceOutput
	7, // 2: WAWebLabyrinthWaWasm.CreateBackupOutput.virtualDevice:type_name -> WAWebLabyrinthWaWasm.VirtualDeviceOutput
	8, // 3: WAWebLabyrinthWaWasm.CreateBackupOutput.epoch0:type_name -> WAWebLabyrinthWaWasm.Epoch0Output
	0, // 4: WAWebLabyrinthWaWasm.LabyrinthWaCommand.createBackupInput:type_name -> WAWebLabyrinthWaWasm.CreateBackupInput
	1, // 5: WAWebLabyrinthWaWasm.LabyrinthWaCommand.encryptMessageInput:type_name -> WAWebLabyrinthWaWasm.EncryptMessageInput
	2, // 6: WAWebLabyrinthWaWasm.LabyrinthWaCommand.decryptMessageInput:type_name -> WAWebLabyrinthWaWasm.DecryptMessageInput
	3, // 7: WAWebLabyrinthWaWasm.LabyrinthWaCommand.orfThreadIDInput:type_name -> WAWebLabyrinthWaWasm.OrfThreadIdInput
	4, // 8: WAWebLabyrinthWaWasm.LabyrinthWaCommand.deriveMessageKeyInput:type_name -> WAWebLabyrinthWaWasm.DeriveMessageKeyInput
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_init() }
func file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_init() {
	if File_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto != nil {
		return
	}
	file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes[14].OneofWrappers = []any{
		(*LabyrinthWaCommand_CreateBackupInput)(nil),
		(*LabyrinthWaCommand_EncryptMessageInput)(nil),
		(*LabyrinthWaCommand_DecryptMessageInput)(nil),
		(*LabyrinthWaCommand_OrfThreadIDInput)(nil),
		(*LabyrinthWaCommand_DeriveMessageKeyInput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDesc), len(file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_goTypes,
		DependencyIndexes: file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_depIdxs,
		MessageInfos:      file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_msgTypes,
	}.Build()
	File_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto = out.File
	file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_goTypes = nil
	file_waWebLabyrinthWaWasm_WAWebLabyrinthWaWasm_proto_depIdxs = nil
}
