// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: waArmadilloBackupCommon/WAArmadilloBackupCommon.proto

package waArmadilloBackupCommon

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subprotocol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	Version       *int32                 `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subprotocol) Reset() {
	*x = Subprotocol{}
	mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subprotocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subprotocol) ProtoMessage() {}

func (x *Subprotocol) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subprotocol.ProtoReflect.Descriptor instead.
func (*Subprotocol) Descriptor() ([]byte, []int) {
	return file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescGZIP(), []int{0}
}

func (x *Subprotocol) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Subprotocol) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type FrankingMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrankingTag   []byte                 `protobuf:"bytes,3,opt,name=frankingTag" json:"frankingTag,omitempty"`
	ReportingTag  []byte                 `protobuf:"bytes,4,opt,name=reportingTag" json:"reportingTag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrankingMetadata) Reset() {
	*x = FrankingMetadata{}
	mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrankingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrankingMetadata) ProtoMessage() {}

func (x *FrankingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrankingMetadata.ProtoReflect.Descriptor instead.
func (*FrankingMetadata) Descriptor() ([]byte, []int) {
	return file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescGZIP(), []int{1}
}

func (x *FrankingMetadata) GetFrankingTag() []byte {
	if x != nil {
		return x.FrankingTag
	}
	return nil
}

func (x *FrankingMetadata) GetReportingTag() []byte {
	if x != nil {
		return x.ReportingTag
	}
	return nil
}

type Metadata struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SenderID            *string                `protobuf:"bytes,1,opt,name=senderID" json:"senderID,omitempty"`
	MessageID           *string                `protobuf:"bytes,2,opt,name=messageID" json:"messageID,omitempty"`
	TimestampMS         *int64                 `protobuf:"varint,3,opt,name=timestampMS" json:"timestampMS,omitempty"`
	FrankingMetadata    *FrankingMetadata      `protobuf:"bytes,4,opt,name=frankingMetadata" json:"frankingMetadata,omitempty"`
	PayloadVersion      *int32                 `protobuf:"varint,5,opt,name=payloadVersion" json:"payloadVersion,omitempty"`
	FutureProofBehavior *int32                 `protobuf:"varint,6,opt,name=futureProofBehavior" json:"futureProofBehavior,omitempty"`
	ThreadTypeTag       *int32                 `protobuf:"varint,7,opt,name=threadTypeTag" json:"threadTypeTag,omitempty"`
	ClientTimestampMS   *int64                 `protobuf:"varint,8,opt,name=clientTimestampMS" json:"clientTimestampMS,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetSenderID() string {
	if x != nil && x.SenderID != nil {
		return *x.SenderID
	}
	return ""
}

func (x *Metadata) GetMessageID() string {
	if x != nil && x.MessageID != nil {
		return *x.MessageID
	}
	return ""
}

func (x *Metadata) GetTimestampMS() int64 {
	if x != nil && x.TimestampMS != nil {
		return *x.TimestampMS
	}
	return 0
}

func (x *Metadata) GetFrankingMetadata() *FrankingMetadata {
	if x != nil {
		return x.FrankingMetadata
	}
	return nil
}

func (x *Metadata) GetPayloadVersion() int32 {
	if x != nil && x.PayloadVersion != nil {
		return *x.PayloadVersion
	}
	return 0
}

func (x *Metadata) GetFutureProofBehavior() int32 {
	if x != nil && x.FutureProofBehavior != nil {
		return *x.FutureProofBehavior
	}
	return 0
}

func (x *Metadata) GetThreadTypeTag() int32 {
	if x != nil && x.ThreadTypeTag != nil {
		return *x.ThreadTypeTag
	}
	return 0
}

func (x *Metadata) GetClientTimestampMS() int64 {
	if x != nil && x.ClientTimestampMS != nil {
		return *x.ClientTimestampMS
	}
	return 0
}

var File_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto protoreflect.FileDescriptor

const file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDesc = "" +
	"\n" +
	"5waArmadilloBackupCommon/WAArmadilloBackupCommon.proto\x12\x17WAArmadilloBackupCommon\"A\n" +
	"\vSubprotocol\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"X\n" +
	"\x10FrankingMetadata\x12 \n" +
	"\vfrankingTag\x18\x03 \x01(\fR\vfrankingTag\x12\"\n" +
	"\freportingTag\x18\x04 \x01(\fR\freportingTag\"\xeb\x02\n" +
	"\bMetadata\x12\x1a\n" +
	"\bsenderID\x18\x01 \x01(\tR\bsenderID\x12\x1c\n" +
	"\tmessageID\x18\x02 \x01(\tR\tmessageID\x12 \n" +
	"\vtimestampMS\x18\x03 \x01(\x03R\vtimestampMS\x12U\n" +
	"\x10frankingMetadata\x18\x04 \x01(\v2).WAArmadilloBackupCommon.FrankingMetadataR\x10frankingMetadata\x12&\n" +
	"\x0epayloadVersion\x18\x05 \x01(\x05R\x0epayloadVersion\x120\n" +
	"\x13futureProofBehavior\x18\x06 \x01(\x05R\x13futureProofBehavior\x12$\n" +
	"\rthreadTypeTag\x18\a \x01(\x05R\rthreadTypeTag\x12,\n" +
	"\x11clientTimestampMS\x18\b \x01(\x03R\x11clientTimestampMSB3Z1go.mau.fi/whatsmeow/proto/waArmadilloBackupCommon"

var (
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescOnce sync.Once
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescData []byte
)

func file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescGZIP() []byte {
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescOnce.Do(func() {
		file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDesc), len(file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDesc)))
	})
	return file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDescData
}

var file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_goTypes = []any{
	(*Subprotocol)(nil),      // 0: WAArmadilloBackupCommon.Subprotocol
	(*FrankingMetadata)(nil), // 1: WAArmadilloBackupCommon.FrankingMetadata
	(*Metadata)(nil),         // 2: WAArmadilloBackupCommon.Metadata
}
var file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_depIdxs = []int32{
	1, // 0: WAArmadilloBackupCommon.Metadata.frankingMetadata:type_name -> WAArmadilloBackupCommon.FrankingMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_init() }
func file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_init() {
	if File_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDesc), len(file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_goTypes,
		DependencyIndexes: file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_depIdxs,
		MessageInfos:      file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_msgTypes,
	}.Build()
	File_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto = out.File
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_goTypes = nil
	file_waArmadilloBackupCommon_WAArmadilloBackupCommon_proto_depIdxs = nil
}
