// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.2
// source: waChatLockSettings/WAProtobufsChatLockSettings.proto

package waChatLockSettings

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	waUserPassword "go.mau.fi/whatsmeow/proto/waUserPassword"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatLockSettings struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	HideLockedChats *bool                        `protobuf:"varint,1,opt,name=hideLockedChats" json:"hideLockedChats,omitempty"`
	SecretCode      *waUserPassword.UserPassword `protobuf:"bytes,2,opt,name=secretCode" json:"secretCode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatLockSettings) Reset() {
	*x = ChatLockSettings{}
	mi := &file_waChatLockSettings_WAProtobufsChatLockSettings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatLockSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatLockSettings) ProtoMessage() {}

func (x *ChatLockSettings) ProtoReflect() protoreflect.Message {
	mi := &file_waChatLockSettings_WAProtobufsChatLockSettings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatLockSettings.ProtoReflect.Descriptor instead.
func (*ChatLockSettings) Descriptor() ([]byte, []int) {
	return file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDescGZIP(), []int{0}
}

func (x *ChatLockSettings) GetHideLockedChats() bool {
	if x != nil && x.HideLockedChats != nil {
		return *x.HideLockedChats
	}
	return false
}

func (x *ChatLockSettings) GetSecretCode() *waUserPassword.UserPassword {
	if x != nil {
		return x.SecretCode
	}
	return nil
}

var File_waChatLockSettings_WAProtobufsChatLockSettings_proto protoreflect.FileDescriptor

var file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDesc = string([]byte{
	0x0a, 0x34, 0x77, 0x61, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x2f, 0x57, 0x41, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73,
	0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x57, 0x41, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x73, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x1a, 0x2c, 0x77, 0x61, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x2f, 0x57, 0x41, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x83, 0x01, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x68, 0x69, 0x64, 0x65, 0x4c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x43, 0x68, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0f, 0x68, 0x69, 0x64, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x43, 0x68, 0x61, 0x74, 0x73,
	0x12, 0x45, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x57, 0x41, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x73, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x53, 0x5a, 0x51, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x68, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x6e, 0x78,
	0x79, 0x7a, 0x2f, 0x61, 0x6d, 0x61, 0x72, 0x6e, 0x61, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x67, 0x6f, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73, 0x6d,
	0x65, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x43, 0x68, 0x61, 0x74,
	0x4c, 0x6f, 0x63, 0x6b, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
})

var (
	file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDescOnce sync.Once
	file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDescData []byte
)

func file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDescGZIP() []byte {
	file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDescOnce.Do(func() {
		file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDesc), len(file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDesc)))
	})
	return file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDescData
}

var file_waChatLockSettings_WAProtobufsChatLockSettings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_waChatLockSettings_WAProtobufsChatLockSettings_proto_goTypes = []any{
	(*ChatLockSettings)(nil),            // 0: WAProtobufsChatLockSettings.ChatLockSettings
	(*waUserPassword.UserPassword)(nil), // 1: WAProtobufsUserPassword.UserPassword
}
var file_waChatLockSettings_WAProtobufsChatLockSettings_proto_depIdxs = []int32{
	1, // 0: WAProtobufsChatLockSettings.ChatLockSettings.secretCode:type_name -> WAProtobufsUserPassword.UserPassword
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_waChatLockSettings_WAProtobufsChatLockSettings_proto_init() }
func file_waChatLockSettings_WAProtobufsChatLockSettings_proto_init() {
	if File_waChatLockSettings_WAProtobufsChatLockSettings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDesc), len(file_waChatLockSettings_WAProtobufsChatLockSettings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waChatLockSettings_WAProtobufsChatLockSettings_proto_goTypes,
		DependencyIndexes: file_waChatLockSettings_WAProtobufsChatLockSettings_proto_depIdxs,
		MessageInfos:      file_waChatLockSettings_WAProtobufsChatLockSettings_proto_msgTypes,
	}.Build()
	File_waChatLockSettings_WAProtobufsChatLockSettings_proto = out.File
	file_waChatLockSettings_WAProtobufsChatLockSettings_proto_goTypes = nil
	file_waChatLockSettings_WAProtobufsChatLockSettings_proto_depIdxs = nil
}
