// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.2
// source: waUserPassword/WAProtobufsUserPassword.proto

package waUserPassword

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserPassword_Transformer int32

const (
	UserPassword_NONE               UserPassword_Transformer = 0
	UserPassword_PBKDF2_HMAC_SHA512 UserPassword_Transformer = 1
	UserPassword_PBKDF2_HMAC_SHA384 UserPassword_Transformer = 2
)

// Enum value maps for UserPassword_Transformer.
var (
	UserPassword_Transformer_name = map[int32]string{
		0: "NONE",
		1: "PBKDF2_HMAC_SHA512",
		2: "PBKDF2_HMAC_SHA384",
	}
	UserPassword_Transformer_value = map[string]int32{
		"NONE":               0,
		"PBKDF2_HMAC_SHA512": 1,
		"PBKDF2_HMAC_SHA384": 2,
	}
)

func (x UserPassword_Transformer) Enum() *UserPassword_Transformer {
	p := new(UserPassword_Transformer)
	*p = x
	return p
}

func (x UserPassword_Transformer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserPassword_Transformer) Descriptor() protoreflect.EnumDescriptor {
	return file_waUserPassword_WAProtobufsUserPassword_proto_enumTypes[0].Descriptor()
}

func (UserPassword_Transformer) Type() protoreflect.EnumType {
	return &file_waUserPassword_WAProtobufsUserPassword_proto_enumTypes[0]
}

func (x UserPassword_Transformer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UserPassword_Transformer) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UserPassword_Transformer(num)
	return nil
}

// Deprecated: Use UserPassword_Transformer.Descriptor instead.
func (UserPassword_Transformer) EnumDescriptor() ([]byte, []int) {
	return file_waUserPassword_WAProtobufsUserPassword_proto_rawDescGZIP(), []int{0, 0}
}

type UserPassword_Encoding int32

const (
	UserPassword_UTF8        UserPassword_Encoding = 0
	UserPassword_UTF8_BROKEN UserPassword_Encoding = 1
)

// Enum value maps for UserPassword_Encoding.
var (
	UserPassword_Encoding_name = map[int32]string{
		0: "UTF8",
		1: "UTF8_BROKEN",
	}
	UserPassword_Encoding_value = map[string]int32{
		"UTF8":        0,
		"UTF8_BROKEN": 1,
	}
)

func (x UserPassword_Encoding) Enum() *UserPassword_Encoding {
	p := new(UserPassword_Encoding)
	*p = x
	return p
}

func (x UserPassword_Encoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserPassword_Encoding) Descriptor() protoreflect.EnumDescriptor {
	return file_waUserPassword_WAProtobufsUserPassword_proto_enumTypes[1].Descriptor()
}

func (UserPassword_Encoding) Type() protoreflect.EnumType {
	return &file_waUserPassword_WAProtobufsUserPassword_proto_enumTypes[1]
}

func (x UserPassword_Encoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UserPassword_Encoding) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UserPassword_Encoding(num)
	return nil
}

// Deprecated: Use UserPassword_Encoding.Descriptor instead.
func (UserPassword_Encoding) EnumDescriptor() ([]byte, []int) {
	return file_waUserPassword_WAProtobufsUserPassword_proto_rawDescGZIP(), []int{0, 1}
}

type UserPassword struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	Encoding        *UserPassword_Encoding         `protobuf:"varint,1,opt,name=encoding,enum=WAProtobufsUserPassword.UserPassword_Encoding" json:"encoding,omitempty"`
	Transformer     *UserPassword_Transformer      `protobuf:"varint,2,opt,name=transformer,enum=WAProtobufsUserPassword.UserPassword_Transformer" json:"transformer,omitempty"`
	TransformerArg  []*UserPassword_TransformerArg `protobuf:"bytes,3,rep,name=transformerArg" json:"transformerArg,omitempty"`
	TransformedData []byte                         `protobuf:"bytes,4,opt,name=transformedData" json:"transformedData,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserPassword) Reset() {
	*x = UserPassword{}
	mi := &file_waUserPassword_WAProtobufsUserPassword_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPassword) ProtoMessage() {}

func (x *UserPassword) ProtoReflect() protoreflect.Message {
	mi := &file_waUserPassword_WAProtobufsUserPassword_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPassword.ProtoReflect.Descriptor instead.
func (*UserPassword) Descriptor() ([]byte, []int) {
	return file_waUserPassword_WAProtobufsUserPassword_proto_rawDescGZIP(), []int{0}
}

func (x *UserPassword) GetEncoding() UserPassword_Encoding {
	if x != nil && x.Encoding != nil {
		return *x.Encoding
	}
	return UserPassword_UTF8
}

func (x *UserPassword) GetTransformer() UserPassword_Transformer {
	if x != nil && x.Transformer != nil {
		return *x.Transformer
	}
	return UserPassword_NONE
}

func (x *UserPassword) GetTransformerArg() []*UserPassword_TransformerArg {
	if x != nil {
		return x.TransformerArg
	}
	return nil
}

func (x *UserPassword) GetTransformedData() []byte {
	if x != nil {
		return x.TransformedData
	}
	return nil
}

type UserPassword_TransformerArg struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Key           *string                            `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value         *UserPassword_TransformerArg_Value `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPassword_TransformerArg) Reset() {
	*x = UserPassword_TransformerArg{}
	mi := &file_waUserPassword_WAProtobufsUserPassword_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPassword_TransformerArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPassword_TransformerArg) ProtoMessage() {}

func (x *UserPassword_TransformerArg) ProtoReflect() protoreflect.Message {
	mi := &file_waUserPassword_WAProtobufsUserPassword_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPassword_TransformerArg.ProtoReflect.Descriptor instead.
func (*UserPassword_TransformerArg) Descriptor() ([]byte, []int) {
	return file_waUserPassword_WAProtobufsUserPassword_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserPassword_TransformerArg) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *UserPassword_TransformerArg) GetValue() *UserPassword_TransformerArg_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type UserPassword_TransformerArg_Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*UserPassword_TransformerArg_Value_AsBlob
	//	*UserPassword_TransformerArg_Value_AsUnsignedInteger
	Value         isUserPassword_TransformerArg_Value_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPassword_TransformerArg_Value) Reset() {
	*x = UserPassword_TransformerArg_Value{}
	mi := &file_waUserPassword_WAProtobufsUserPassword_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPassword_TransformerArg_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPassword_TransformerArg_Value) ProtoMessage() {}

func (x *UserPassword_TransformerArg_Value) ProtoReflect() protoreflect.Message {
	mi := &file_waUserPassword_WAProtobufsUserPassword_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPassword_TransformerArg_Value.ProtoReflect.Descriptor instead.
func (*UserPassword_TransformerArg_Value) Descriptor() ([]byte, []int) {
	return file_waUserPassword_WAProtobufsUserPassword_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *UserPassword_TransformerArg_Value) GetValue() isUserPassword_TransformerArg_Value_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UserPassword_TransformerArg_Value) GetAsBlob() []byte {
	if x != nil {
		if x, ok := x.Value.(*UserPassword_TransformerArg_Value_AsBlob); ok {
			return x.AsBlob
		}
	}
	return nil
}

func (x *UserPassword_TransformerArg_Value) GetAsUnsignedInteger() uint32 {
	if x != nil {
		if x, ok := x.Value.(*UserPassword_TransformerArg_Value_AsUnsignedInteger); ok {
			return x.AsUnsignedInteger
		}
	}
	return 0
}

type isUserPassword_TransformerArg_Value_Value interface {
	isUserPassword_TransformerArg_Value_Value()
}

type UserPassword_TransformerArg_Value_AsBlob struct {
	AsBlob []byte `protobuf:"bytes,1,opt,name=asBlob,oneof"`
}

type UserPassword_TransformerArg_Value_AsUnsignedInteger struct {
	AsUnsignedInteger uint32 `protobuf:"varint,2,opt,name=asUnsignedInteger,oneof"`
}

func (*UserPassword_TransformerArg_Value_AsBlob) isUserPassword_TransformerArg_Value_Value() {}

func (*UserPassword_TransformerArg_Value_AsUnsignedInteger) isUserPassword_TransformerArg_Value_Value() {
}

var File_waUserPassword_WAProtobufsUserPassword_proto protoreflect.FileDescriptor

var file_waUserPassword_WAProtobufsUserPassword_proto_rawDesc = string([]byte{
	0x0a, 0x2c, 0x77, 0x61, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x2f, 0x57, 0x41, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17,
	0x57, 0x41, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xfa, 0x04, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x4a, 0x0a, 0x08, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x57, 0x41, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x12, 0x53, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x31, 0x2e, 0x57, 0x41, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x52, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x12, 0x5c, 0x0a, 0x0e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x41, 0x72, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x34, 0x2e, 0x57, 0x41, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x65, 0x72, 0x41, 0x72, 0x67, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x65, 0x72, 0x41, 0x72, 0x67, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x64, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0xd0, 0x01, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65,
	0x72, 0x41, 0x72, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x50, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x57, 0x41, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x73, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x41, 0x72, 0x67, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x5a, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x18, 0x0a, 0x06, 0x61, 0x73, 0x42, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x06, 0x61, 0x73, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x2e, 0x0a, 0x11, 0x61,
	0x73, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x11, 0x61, 0x73, 0x55, 0x6e, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x47, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x65, 0x72, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x16, 0x0a,
	0x12, 0x50, 0x42, 0x4b, 0x44, 0x46, 0x32, 0x5f, 0x48, 0x4d, 0x41, 0x43, 0x5f, 0x53, 0x48, 0x41,
	0x35, 0x31, 0x32, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x42, 0x4b, 0x44, 0x46, 0x32, 0x5f,
	0x48, 0x4d, 0x41, 0x43, 0x5f, 0x53, 0x48, 0x41, 0x33, 0x38, 0x34, 0x10, 0x02, 0x22, 0x25, 0x0a,
	0x08, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x54, 0x46,
	0x38, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x54, 0x46, 0x38, 0x5f, 0x42, 0x52, 0x4f, 0x4b,
	0x45, 0x4e, 0x10, 0x01, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x68, 0x65, 0x6e, 0x61, 0x74, 0x65, 0x6e, 0x78, 0x79, 0x7a, 0x2f,
	0x61, 0x6d, 0x61, 0x72, 0x6e, 0x61, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x67,
	0x6f, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x77, 0x68, 0x61, 0x74, 0x73, 0x6d, 0x65, 0x6f, 0x77,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x61, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64,
})

var (
	file_waUserPassword_WAProtobufsUserPassword_proto_rawDescOnce sync.Once
	file_waUserPassword_WAProtobufsUserPassword_proto_rawDescData []byte
)

func file_waUserPassword_WAProtobufsUserPassword_proto_rawDescGZIP() []byte {
	file_waUserPassword_WAProtobufsUserPassword_proto_rawDescOnce.Do(func() {
		file_waUserPassword_WAProtobufsUserPassword_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waUserPassword_WAProtobufsUserPassword_proto_rawDesc), len(file_waUserPassword_WAProtobufsUserPassword_proto_rawDesc)))
	})
	return file_waUserPassword_WAProtobufsUserPassword_proto_rawDescData
}

var file_waUserPassword_WAProtobufsUserPassword_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_waUserPassword_WAProtobufsUserPassword_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_waUserPassword_WAProtobufsUserPassword_proto_goTypes = []any{
	(UserPassword_Transformer)(0),             // 0: WAProtobufsUserPassword.UserPassword.Transformer
	(UserPassword_Encoding)(0),                // 1: WAProtobufsUserPassword.UserPassword.Encoding
	(*UserPassword)(nil),                      // 2: WAProtobufsUserPassword.UserPassword
	(*UserPassword_TransformerArg)(nil),       // 3: WAProtobufsUserPassword.UserPassword.TransformerArg
	(*UserPassword_TransformerArg_Value)(nil), // 4: WAProtobufsUserPassword.UserPassword.TransformerArg.Value
}
var file_waUserPassword_WAProtobufsUserPassword_proto_depIdxs = []int32{
	1, // 0: WAProtobufsUserPassword.UserPassword.encoding:type_name -> WAProtobufsUserPassword.UserPassword.Encoding
	0, // 1: WAProtobufsUserPassword.UserPassword.transformer:type_name -> WAProtobufsUserPassword.UserPassword.Transformer
	3, // 2: WAProtobufsUserPassword.UserPassword.transformerArg:type_name -> WAProtobufsUserPassword.UserPassword.TransformerArg
	4, // 3: WAProtobufsUserPassword.UserPassword.TransformerArg.value:type_name -> WAProtobufsUserPassword.UserPassword.TransformerArg.Value
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_waUserPassword_WAProtobufsUserPassword_proto_init() }
func file_waUserPassword_WAProtobufsUserPassword_proto_init() {
	if File_waUserPassword_WAProtobufsUserPassword_proto != nil {
		return
	}
	file_waUserPassword_WAProtobufsUserPassword_proto_msgTypes[2].OneofWrappers = []any{
		(*UserPassword_TransformerArg_Value_AsBlob)(nil),
		(*UserPassword_TransformerArg_Value_AsUnsignedInteger)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waUserPassword_WAProtobufsUserPassword_proto_rawDesc), len(file_waUserPassword_WAProtobufsUserPassword_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waUserPassword_WAProtobufsUserPassword_proto_goTypes,
		DependencyIndexes: file_waUserPassword_WAProtobufsUserPassword_proto_depIdxs,
		EnumInfos:         file_waUserPassword_WAProtobufsUserPassword_proto_enumTypes,
		MessageInfos:      file_waUserPassword_WAProtobufsUserPassword_proto_msgTypes,
	}.Build()
	File_waUserPassword_WAProtobufsUserPassword_proto = out.File
	file_waUserPassword_WAProtobufsUserPassword_proto_goTypes = nil
	file_waUserPassword_WAProtobufsUserPassword_proto_depIdxs = nil
}
