// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: waArmadilloBackupMessage/WAArmadilloBackupMessage.proto

package waArmadilloBackupMessage

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	waArmadilloBackupCommon "go.mau.fi/whatsmeow/proto/waArmadilloBackupCommon"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BackupMessage_EncryptedTransportMessage
	//	*BackupMessage_EncryptedTransportEvent
	//	*BackupMessage_EncryptedTransportLocallyTransformedMessage
	//	*BackupMessage_MiTransportAdminMessage
	Payload       isBackupMessage_Payload           `protobuf_oneof:"payload"`
	Metadata      *waArmadilloBackupCommon.Metadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupMessage) Reset() {
	*x = BackupMessage{}
	mi := &file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupMessage) ProtoMessage() {}

func (x *BackupMessage) ProtoReflect() protoreflect.Message {
	mi := &file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupMessage.ProtoReflect.Descriptor instead.
func (*BackupMessage) Descriptor() ([]byte, []int) {
	return file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDescGZIP(), []int{0}
}

func (x *BackupMessage) GetPayload() isBackupMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BackupMessage) GetEncryptedTransportMessage() []byte {
	if x != nil {
		if x, ok := x.Payload.(*BackupMessage_EncryptedTransportMessage); ok {
			return x.EncryptedTransportMessage
		}
	}
	return nil
}

func (x *BackupMessage) GetEncryptedTransportEvent() *waArmadilloBackupCommon.Subprotocol {
	if x != nil {
		if x, ok := x.Payload.(*BackupMessage_EncryptedTransportEvent); ok {
			return x.EncryptedTransportEvent
		}
	}
	return nil
}

func (x *BackupMessage) GetEncryptedTransportLocallyTransformedMessage() *waArmadilloBackupCommon.Subprotocol {
	if x != nil {
		if x, ok := x.Payload.(*BackupMessage_EncryptedTransportLocallyTransformedMessage); ok {
			return x.EncryptedTransportLocallyTransformedMessage
		}
	}
	return nil
}

func (x *BackupMessage) GetMiTransportAdminMessage() *waArmadilloBackupCommon.Subprotocol {
	if x != nil {
		if x, ok := x.Payload.(*BackupMessage_MiTransportAdminMessage); ok {
			return x.MiTransportAdminMessage
		}
	}
	return nil
}

func (x *BackupMessage) GetMetadata() *waArmadilloBackupCommon.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isBackupMessage_Payload interface {
	isBackupMessage_Payload()
}

type BackupMessage_EncryptedTransportMessage struct {
	EncryptedTransportMessage []byte `protobuf:"bytes,2,opt,name=encryptedTransportMessage,oneof"`
}

type BackupMessage_EncryptedTransportEvent struct {
	EncryptedTransportEvent *waArmadilloBackupCommon.Subprotocol `protobuf:"bytes,5,opt,name=encryptedTransportEvent,oneof"`
}

type BackupMessage_EncryptedTransportLocallyTransformedMessage struct {
	EncryptedTransportLocallyTransformedMessage *waArmadilloBackupCommon.Subprotocol `protobuf:"bytes,6,opt,name=encryptedTransportLocallyTransformedMessage,oneof"`
}

type BackupMessage_MiTransportAdminMessage struct {
	MiTransportAdminMessage *waArmadilloBackupCommon.Subprotocol `protobuf:"bytes,7,opt,name=miTransportAdminMessage,oneof"`
}

func (*BackupMessage_EncryptedTransportMessage) isBackupMessage_Payload() {}

func (*BackupMessage_EncryptedTransportEvent) isBackupMessage_Payload() {}

func (*BackupMessage_EncryptedTransportLocallyTransformedMessage) isBackupMessage_Payload() {}

func (*BackupMessage_MiTransportAdminMessage) isBackupMessage_Payload() {}

var File_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto protoreflect.FileDescriptor

const file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDesc = "" +
	"\n" +
	"7waArmadilloBackupMessage/WAArmadilloBackupMessage.proto\x12\x18WAArmadilloBackupMessage\x1a5waArmadilloBackupCommon/WAArmadilloBackupCommon.proto\"\xe8\x03\n" +
	"\rBackupMessage\x12>\n" +
	"\x19encryptedTransportMessage\x18\x02 \x01(\fH\x00R\x19encryptedTransportMessage\x12`\n" +
	"\x17encryptedTransportEvent\x18\x05 \x01(\v2$.WAArmadilloBackupCommon.SubprotocolH\x00R\x17encryptedTransportEvent\x12\x88\x01\n" +
	"+encryptedTransportLocallyTransformedMessage\x18\x06 \x01(\v2$.WAArmadilloBackupCommon.SubprotocolH\x00R+encryptedTransportLocallyTransformedMessage\x12`\n" +
	"\x17miTransportAdminMessage\x18\a \x01(\v2$.WAArmadilloBackupCommon.SubprotocolH\x00R\x17miTransportAdminMessage\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2!.WAArmadilloBackupCommon.MetadataR\bmetadataB\t\n" +
	"\apayloadB4Z2go.mau.fi/whatsmeow/proto/waArmadilloBackupMessage"

var (
	file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDescOnce sync.Once
	file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDescData []byte
)

func file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDescGZIP() []byte {
	file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDescOnce.Do(func() {
		file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDesc), len(file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDesc)))
	})
	return file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDescData
}

var file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_goTypes = []any{
	(*BackupMessage)(nil),                       // 0: WAArmadilloBackupMessage.BackupMessage
	(*waArmadilloBackupCommon.Subprotocol)(nil), // 1: WAArmadilloBackupCommon.Subprotocol
	(*waArmadilloBackupCommon.Metadata)(nil),    // 2: WAArmadilloBackupCommon.Metadata
}
var file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_depIdxs = []int32{
	1, // 0: WAArmadilloBackupMessage.BackupMessage.encryptedTransportEvent:type_name -> WAArmadilloBackupCommon.Subprotocol
	1, // 1: WAArmadilloBackupMessage.BackupMessage.encryptedTransportLocallyTransformedMessage:type_name -> WAArmadilloBackupCommon.Subprotocol
	1, // 2: WAArmadilloBackupMessage.BackupMessage.miTransportAdminMessage:type_name -> WAArmadilloBackupCommon.Subprotocol
	2, // 3: WAArmadilloBackupMessage.BackupMessage.metadata:type_name -> WAArmadilloBackupCommon.Metadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_init() }
func file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_init() {
	if File_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto != nil {
		return
	}
	file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_msgTypes[0].OneofWrappers = []any{
		(*BackupMessage_EncryptedTransportMessage)(nil),
		(*BackupMessage_EncryptedTransportEvent)(nil),
		(*BackupMessage_EncryptedTransportLocallyTransformedMessage)(nil),
		(*BackupMessage_MiTransportAdminMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDesc), len(file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_goTypes,
		DependencyIndexes: file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_depIdxs,
		MessageInfos:      file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_msgTypes,
	}.Build()
	File_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto = out.File
	file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_goTypes = nil
	file_waArmadilloBackupMessage_WAArmadilloBackupMessage_proto_depIdxs = nil
}
