// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: waGroupHistory/WAWebProtobufsGroupHistory.proto

package waGroupHistory

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	waCommon "go.mau.fi/whatsmeow/proto/waCommon"
	waWeb "go.mau.fi/whatsmeow/proto/waWeb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupHistory struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	Messages               []*waWeb.WebMessageInfo  `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	AssociatedMessageLists []*AssociatedMessageList `protobuf:"bytes,2,rep,name=associatedMessageLists" json:"associatedMessageLists,omitempty"`
	CommentMessages        []*waWeb.WebMessageInfo  `protobuf:"bytes,3,rep,name=commentMessages" json:"commentMessages,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GroupHistory) Reset() {
	*x = GroupHistory{}
	mi := &file_waGroupHistory_WAWebProtobufsGroupHistory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupHistory) ProtoMessage() {}

func (x *GroupHistory) ProtoReflect() protoreflect.Message {
	mi := &file_waGroupHistory_WAWebProtobufsGroupHistory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupHistory.ProtoReflect.Descriptor instead.
func (*GroupHistory) Descriptor() ([]byte, []int) {
	return file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDescGZIP(), []int{0}
}

func (x *GroupHistory) GetMessages() []*waWeb.WebMessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GroupHistory) GetAssociatedMessageLists() []*AssociatedMessageList {
	if x != nil {
		return x.AssociatedMessageLists
	}
	return nil
}

func (x *GroupHistory) GetCommentMessages() []*waWeb.WebMessageInfo {
	if x != nil {
		return x.CommentMessages
	}
	return nil
}

type AssociatedMessageList struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Messages        []*waWeb.WebMessageInfo `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	ParentMessage   *waCommon.MessageKey    `protobuf:"bytes,2,opt,name=parentMessage" json:"parentMessage,omitempty"`
	AssociationType *int32                  `protobuf:"varint,3,opt,name=associationType" json:"associationType,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AssociatedMessageList) Reset() {
	*x = AssociatedMessageList{}
	mi := &file_waGroupHistory_WAWebProtobufsGroupHistory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociatedMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociatedMessageList) ProtoMessage() {}

func (x *AssociatedMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_waGroupHistory_WAWebProtobufsGroupHistory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociatedMessageList.ProtoReflect.Descriptor instead.
func (*AssociatedMessageList) Descriptor() ([]byte, []int) {
	return file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDescGZIP(), []int{1}
}

func (x *AssociatedMessageList) GetMessages() []*waWeb.WebMessageInfo {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *AssociatedMessageList) GetParentMessage() *waCommon.MessageKey {
	if x != nil {
		return x.ParentMessage
	}
	return nil
}

func (x *AssociatedMessageList) GetAssociationType() int32 {
	if x != nil && x.AssociationType != nil {
		return *x.AssociationType
	}
	return 0
}

var File_waGroupHistory_WAWebProtobufsGroupHistory_proto protoreflect.FileDescriptor

const file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDesc = "" +
	"\n" +
	"/waGroupHistory/WAWebProtobufsGroupHistory.proto\x12\x1aWAWebProtobufsGroupHistory\x1a\x17waCommon/WACommon.proto\x1a\x1dwaWeb/WAWebProtobufsWeb.proto\"\x85\x02\n" +
	"\fGroupHistory\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2!.WAWebProtobufsWeb.WebMessageInfoR\bmessages\x12i\n" +
	"\x16associatedMessageLists\x18\x02 \x03(\v21.WAWebProtobufsGroupHistory.AssociatedMessageListR\x16associatedMessageLists\x12K\n" +
	"\x0fcommentMessages\x18\x03 \x03(\v2!.WAWebProtobufsWeb.WebMessageInfoR\x0fcommentMessages\"\xbc\x01\n" +
	"\x15AssociatedMessageList\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2!.WAWebProtobufsWeb.WebMessageInfoR\bmessages\x12:\n" +
	"\rparentMessage\x18\x02 \x01(\v2\x14.WACommon.MessageKeyR\rparentMessage\x12(\n" +
	"\x0fassociationType\x18\x03 \x01(\x05R\x0fassociationTypeB*Z(go.mau.fi/whatsmeow/proto/waGroupHistory"

var (
	file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDescOnce sync.Once
	file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDescData []byte
)

func file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDescGZIP() []byte {
	file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDescOnce.Do(func() {
		file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDesc), len(file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDesc)))
	})
	return file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDescData
}

var file_waGroupHistory_WAWebProtobufsGroupHistory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_waGroupHistory_WAWebProtobufsGroupHistory_proto_goTypes = []any{
	(*GroupHistory)(nil),          // 0: WAWebProtobufsGroupHistory.GroupHistory
	(*AssociatedMessageList)(nil), // 1: WAWebProtobufsGroupHistory.AssociatedMessageList
	(*waWeb.WebMessageInfo)(nil),  // 2: WAWebProtobufsWeb.WebMessageInfo
	(*waCommon.MessageKey)(nil),   // 3: WACommon.MessageKey
}
var file_waGroupHistory_WAWebProtobufsGroupHistory_proto_depIdxs = []int32{
	2, // 0: WAWebProtobufsGroupHistory.GroupHistory.messages:type_name -> WAWebProtobufsWeb.WebMessageInfo
	1, // 1: WAWebProtobufsGroupHistory.GroupHistory.associatedMessageLists:type_name -> WAWebProtobufsGroupHistory.AssociatedMessageList
	2, // 2: WAWebProtobufsGroupHistory.GroupHistory.commentMessages:type_name -> WAWebProtobufsWeb.WebMessageInfo
	2, // 3: WAWebProtobufsGroupHistory.AssociatedMessageList.messages:type_name -> WAWebProtobufsWeb.WebMessageInfo
	3, // 4: WAWebProtobufsGroupHistory.AssociatedMessageList.parentMessage:type_name -> WACommon.MessageKey
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_waGroupHistory_WAWebProtobufsGroupHistory_proto_init() }
func file_waGroupHistory_WAWebProtobufsGroupHistory_proto_init() {
	if File_waGroupHistory_WAWebProtobufsGroupHistory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDesc), len(file_waGroupHistory_WAWebProtobufsGroupHistory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waGroupHistory_WAWebProtobufsGroupHistory_proto_goTypes,
		DependencyIndexes: file_waGroupHistory_WAWebProtobufsGroupHistory_proto_depIdxs,
		MessageInfos:      file_waGroupHistory_WAWebProtobufsGroupHistory_proto_msgTypes,
	}.Build()
	File_waGroupHistory_WAWebProtobufsGroupHistory_proto = out.File
	file_waGroupHistory_WAWebProtobufsGroupHistory_proto_goTypes = nil
	file_waGroupHistory_WAWebProtobufsGroupHistory_proto_depIdxs = nil
}
