// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.2
// source: waEphemeral/WAWebProtobufsEphemeral.proto

package waEphemeral

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EphemeralSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      *int32                 `protobuf:"fixed32,1,opt,name=duration" json:"duration,omitempty"`
	Timestamp     *int64                 `protobuf:"fixed64,2,opt,name=timestamp" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EphemeralSetting) Reset() {
	*x = EphemeralSetting{}
	mi := &file_waEphemeral_WAWebProtobufsEphemeral_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EphemeralSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EphemeralSetting) ProtoMessage() {}

func (x *EphemeralSetting) ProtoReflect() protoreflect.Message {
	mi := &file_waEphemeral_WAWebProtobufsEphemeral_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EphemeralSetting.ProtoReflect.Descriptor instead.
func (*EphemeralSetting) Descriptor() ([]byte, []int) {
	return file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDescGZIP(), []int{0}
}

func (x *EphemeralSetting) GetDuration() int32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *EphemeralSetting) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

var File_waEphemeral_WAWebProtobufsEphemeral_proto protoreflect.FileDescriptor

var file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDesc = string([]byte{
	0x0a, 0x29, 0x77, 0x61, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x2f, 0x57, 0x41,
	0x57, 0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x45, 0x70, 0x68, 0x65,
	0x6d, 0x65, 0x72, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x57, 0x41, 0x57,
	0x65, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x45, 0x70, 0x68, 0x65, 0x6d,
	0x65, 0x72, 0x61, 0x6c, 0x22, 0x4c, 0x0a, 0x10, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61,
	0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0f, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x10, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x6f, 0x2e, 0x6d, 0x61, 0x75, 0x2e, 0x66, 0x69, 0x2f,
	0x77, 0x68, 0x61, 0x74, 0x73, 0x6d, 0x65, 0x6f, 0x77, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x77, 0x61, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c,
})

var (
	file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDescOnce sync.Once
	file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDescData []byte
)

func file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDescGZIP() []byte {
	file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDescOnce.Do(func() {
		file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDesc), len(file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDesc)))
	})
	return file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDescData
}

var file_waEphemeral_WAWebProtobufsEphemeral_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_waEphemeral_WAWebProtobufsEphemeral_proto_goTypes = []any{
	(*EphemeralSetting)(nil), // 0: WAWebProtobufsEphemeral.EphemeralSetting
}
var file_waEphemeral_WAWebProtobufsEphemeral_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_waEphemeral_WAWebProtobufsEphemeral_proto_init() }
func file_waEphemeral_WAWebProtobufsEphemeral_proto_init() {
	if File_waEphemeral_WAWebProtobufsEphemeral_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDesc), len(file_waEphemeral_WAWebProtobufsEphemeral_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waEphemeral_WAWebProtobufsEphemeral_proto_goTypes,
		DependencyIndexes: file_waEphemeral_WAWebProtobufsEphemeral_proto_depIdxs,
		MessageInfos:      file_waEphemeral_WAWebProtobufsEphemeral_proto_msgTypes,
	}.Build()
	File_waEphemeral_WAWebProtobufsEphemeral_proto = out.File
	file_waEphemeral_WAWebProtobufsEphemeral_proto_goTypes = nil
	file_waEphemeral_WAWebProtobufsEphemeral_proto_depIdxs = nil
}
