// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: waFingerprint/WAFingerprint.proto

package waFingerprint

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	_ "embed"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostedState int32

const (
	HostedState_E2EE   HostedState = 0
	HostedState_HOSTED HostedState = 1
)

// Enum value maps for HostedState.
var (
	HostedState_name = map[int32]string{
		0: "E2EE",
		1: "HOSTED",
	}
	HostedState_value = map[string]int32{
		"E2EE":   0,
		"HOSTED": 1,
	}
)

func (x HostedState) Enum() *HostedState {
	p := new(HostedState)
	*p = x
	return p
}

func (x HostedState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostedState) Descriptor() protoreflect.EnumDescriptor {
	return file_waFingerprint_WAFingerprint_proto_enumTypes[0].Descriptor()
}

func (HostedState) Type() protoreflect.EnumType {
	return &file_waFingerprint_WAFingerprint_proto_enumTypes[0]
}

func (x HostedState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HostedState) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HostedState(num)
	return nil
}

// Deprecated: Use HostedState.Descriptor instead.
func (HostedState) EnumDescriptor() ([]byte, []int) {
	return file_waFingerprint_WAFingerprint_proto_rawDescGZIP(), []int{0}
}

type FingerprintData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey          []byte       `protobuf:"bytes,1,opt,name=publicKey" json:"publicKey,omitempty"`
	PnIdentifier       []byte       `protobuf:"bytes,2,opt,name=pnIdentifier" json:"pnIdentifier,omitempty"`
	LidIdentifier      []byte       `protobuf:"bytes,3,opt,name=lidIdentifier" json:"lidIdentifier,omitempty"`
	UsernameIdentifier []byte       `protobuf:"bytes,4,opt,name=usernameIdentifier" json:"usernameIdentifier,omitempty"`
	HostedState        *HostedState `protobuf:"varint,5,opt,name=hostedState,enum=WAFingerprint.HostedState" json:"hostedState,omitempty"`
}

func (x *FingerprintData) Reset() {
	*x = FingerprintData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waFingerprint_WAFingerprint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FingerprintData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintData) ProtoMessage() {}

func (x *FingerprintData) ProtoReflect() protoreflect.Message {
	mi := &file_waFingerprint_WAFingerprint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FingerprintData.ProtoReflect.Descriptor instead.
func (*FingerprintData) Descriptor() ([]byte, []int) {
	return file_waFingerprint_WAFingerprint_proto_rawDescGZIP(), []int{0}
}

func (x *FingerprintData) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *FingerprintData) GetPnIdentifier() []byte {
	if x != nil {
		return x.PnIdentifier
	}
	return nil
}

func (x *FingerprintData) GetLidIdentifier() []byte {
	if x != nil {
		return x.LidIdentifier
	}
	return nil
}

func (x *FingerprintData) GetUsernameIdentifier() []byte {
	if x != nil {
		return x.UsernameIdentifier
	}
	return nil
}

func (x *FingerprintData) GetHostedState() HostedState {
	if x != nil && x.HostedState != nil {
		return *x.HostedState
	}
	return HostedState_E2EE
}

type CombinedFingerprint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version           *uint32          `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	LocalFingerprint  *FingerprintData `protobuf:"bytes,2,opt,name=localFingerprint" json:"localFingerprint,omitempty"`
	RemoteFingerprint *FingerprintData `protobuf:"bytes,3,opt,name=remoteFingerprint" json:"remoteFingerprint,omitempty"`
}

func (x *CombinedFingerprint) Reset() {
	*x = CombinedFingerprint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_waFingerprint_WAFingerprint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CombinedFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedFingerprint) ProtoMessage() {}

func (x *CombinedFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_waFingerprint_WAFingerprint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedFingerprint.ProtoReflect.Descriptor instead.
func (*CombinedFingerprint) Descriptor() ([]byte, []int) {
	return file_waFingerprint_WAFingerprint_proto_rawDescGZIP(), []int{1}
}

func (x *CombinedFingerprint) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *CombinedFingerprint) GetLocalFingerprint() *FingerprintData {
	if x != nil {
		return x.LocalFingerprint
	}
	return nil
}

func (x *CombinedFingerprint) GetRemoteFingerprint() *FingerprintData {
	if x != nil {
		return x.RemoteFingerprint
	}
	return nil
}

var File_waFingerprint_WAFingerprint_proto protoreflect.FileDescriptor

//go:embed WAFingerprint.pb.raw
var file_waFingerprint_WAFingerprint_proto_rawDesc []byte

var (
	file_waFingerprint_WAFingerprint_proto_rawDescOnce sync.Once
	file_waFingerprint_WAFingerprint_proto_rawDescData = file_waFingerprint_WAFingerprint_proto_rawDesc
)

func file_waFingerprint_WAFingerprint_proto_rawDescGZIP() []byte {
	file_waFingerprint_WAFingerprint_proto_rawDescOnce.Do(func() {
		file_waFingerprint_WAFingerprint_proto_rawDescData = protoimpl.X.CompressGZIP(file_waFingerprint_WAFingerprint_proto_rawDescData)
	})
	return file_waFingerprint_WAFingerprint_proto_rawDescData
}

var file_waFingerprint_WAFingerprint_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_waFingerprint_WAFingerprint_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_waFingerprint_WAFingerprint_proto_goTypes = []any{
	(HostedState)(0),            // 0: WAFingerprint.HostedState
	(*FingerprintData)(nil),     // 1: WAFingerprint.FingerprintData
	(*CombinedFingerprint)(nil), // 2: WAFingerprint.CombinedFingerprint
}
var file_waFingerprint_WAFingerprint_proto_depIdxs = []int32{
	0, // 0: WAFingerprint.FingerprintData.hostedState:type_name -> WAFingerprint.HostedState
	1, // 1: WAFingerprint.CombinedFingerprint.localFingerprint:type_name -> WAFingerprint.FingerprintData
	1, // 2: WAFingerprint.CombinedFingerprint.remoteFingerprint:type_name -> WAFingerprint.FingerprintData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_waFingerprint_WAFingerprint_proto_init() }
func file_waFingerprint_WAFingerprint_proto_init() {
	if File_waFingerprint_WAFingerprint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_waFingerprint_WAFingerprint_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FingerprintData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_waFingerprint_WAFingerprint_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CombinedFingerprint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_waFingerprint_WAFingerprint_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_waFingerprint_WAFingerprint_proto_goTypes,
		DependencyIndexes: file_waFingerprint_WAFingerprint_proto_depIdxs,
		EnumInfos:         file_waFingerprint_WAFingerprint_proto_enumTypes,
		MessageInfos:      file_waFingerprint_WAFingerprint_proto_msgTypes,
	}.Build()
	File_waFingerprint_WAFingerprint_proto = out.File
	file_waFingerprint_WAFingerprint_proto_rawDesc = nil
	file_waFingerprint_WAFingerprint_proto_goTypes = nil
	file_waFingerprint_WAFingerprint_proto_depIdxs = nil
}
